### ISSUE TITLE
System.Net.Logging does not seem to be a valid type anymore

### ISSUE THREAD

**Issue by webJose** [jhilgeman/HttpRawTraceListener#1]
Don't know with which framework this ever worked, but I tried .Net Framework 4 to 4.71, and all .Net Core versions.  None work, all fail at the same line.

The problem:  The type System.Net.Logging does not seem to exist, at least not in the same assembly as System.Net.Sockets.Socket.  So line 116 yields null, and then line 120 throws a NullReferenceException.

**Comment by AKlaus** [comment]
Confirm the issue.
My call stack:
```
System.NullReferenceException
Object reference not set to an instance of an object.
   at System.Diagnostics.HttpRawTraceListener.enableTracing() in HttpRawTraceListener.cs:line 119
   at System.Diagnostics.HttpRawTraceListener.Initialize() in HttpRawTraceListener.cs:line 71
```
